planning_plugins:
  - pilz_industrial_motion_planner/CommandPlanner

# Pre-processing steps applied before the planner runs
request_adapters:
  - default_planning_request_adapters/ResolveConstraintFrames
  - default_planning_request_adapters/ValidateWorkspaceBounds
  - default_planning_request_adapters/CheckStartStateBounds
  - default_planning_request_adapters/CheckStartStateCollision

# Post-processing steps applied to the trajectory after planning
response_adapters:
  - default_planning_response_adapters/DisplayMotionPath
